steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/scooter-repo/scooter-linked-bot', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/scooter-repo/scooter-linked-bot']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'scooter-bot-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/scooter-repo/scooter-linked-bot'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'

# Store images in Artifact Registry (replaces Google Container Registry)
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/scooter-repo/scooter-linked-bot'
